### ISSUE TITLE
Error when trying to establish a connection using the example on this page

### ISSUE THREAD

**Issue by bartmcleod** [MicrosoftDocs/azure-docs.nl-nl#82]
connect_ex() takes exactly one argument (2 given)
Traceback (most recent call last):
  File "$HOME/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "$HOME/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "$HOME/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "$HOME/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "$HOME/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "~/.azure/cliextensions/webapp/azext_webapp/custom.py", line 248, in create_tunnel
    tunnel_server = TunnelServer('', port, host_name, user_name, user_password)
  File "$HOME/.azure/cliextensions/webapp/azext_webapp/tunnel.py", line 42, in __init__
    if self.local_port != 0 and not self.is_port_open():
  File "$HOME/.azure/cliextensions/webapp/azext_webapp/tunnel.py", line 69, in is_port_open
    if sock.connect_ex('', self.local_port) == 0:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: connect_ex() takes exactly one argument (2 given)

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14436](https://github.com/MicrosoftDocs/azure-docs/issues/14436) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @bartmcleod ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14436.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
